### ISSUE TITLE
Not working on monthly-choice page

### ISSUE THREAD

**Issue by ProblemFactory** [MrMarble/humble-bundle-extra#5]
I checked today it seems that the script is not working (probably because of UI changes).

**Comment by MrMarble** [comment]
Could you provide more info?

I tried it and is working on the Choice page: 
![imagen](https://user-images.githubusercontent.com/4268580/124351240-89319600-dbf9-11eb-8957-10e63c8fab6a.png)

Currently, the only bundle available is for Epic store, not steam, that's why there's no info there

**Comment by ProblemFactory** [comment]
![image](https://user-images.githubusercontent.com/2966492/124351385-c45aa780-dbae-11eb-9043-767bd98223fb.png)

I already redeemed the first two games. It is still not shown as owned.

**Comment by ProblemFactory** [comment]
I was on this page: https://www.humblebundle.com/subscription/june-2021

**Comment by MrMarble** [comment]
Yes, that's related to #2 and #3, to reduce network activity the requests to steam are cached (because of the thousand of results), currently the only way of clearing the cache is manually deleting `localStorage`.

Will try to fix it as soon as I have time

**Comment by MrMarble** [comment]
> 
> 
> I was on this page: https://www.humblebundle.com/subscription/june-2021

See, that's a different issue, for some reason that page is not being detected by the script, will be added as well

**Comment by ProblemFactory** [comment]
OK thanks.
